blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://faserf.github.io/ha-whatsapp/
    about: Read the documentation before opening an issue.
  - name: App Issues
    url: https://github.com/FaserF/hassio-addons/issues
    about: Please report issues with the App (not the Integration) here.
