name: CI Orchestrator

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      resource_profile:
        description: 'Resource Profile'
        required: true
        default: 'Economy'
        type: choice
        options:
          - Economy
          - Full
  workflow_call:
    inputs:
      resource_profile:
        description: 'Resource Profile'
        required: false
        default: 'Economy'
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v6
      - name: üè∑Ô∏è Sync Labels
        uses: actions/labeler@v6
        with:
          repo-token: ${{ github.token }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - '!(docs/**|**/*.md)'
              - '*'

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    needs: [changes, lint]
    if: needs.changes.outputs.code == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/test.yml
    with:
      profile: ${{ inputs.resource_profile || 'Economy' }}

  build:
    needs: [changes, test]
    if: needs.changes.outputs.code == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build.yml
    with:
      profile: ${{ inputs.resource_profile || 'Economy' }}
